-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 00:27:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `id` INT NULL AUTO_INCREMENT,
  `RAZONSOCIAL` VARCHAR(45) NOT NULL,
  `CUIT` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIOS` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIOCLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIOCLIENTE` (
  `id` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idServicio` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idServicio_idx` (`idServicio` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`CLIENTES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `mydb`.`SERVICIOS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TECNICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TECNICOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIOTECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIOTECNICO` (
  `in` INT NOT NULL AUTO_INCREMENT,
  `idTecnico` INT NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`in`),
  INDEX `idTecnico_idx` (`idTecnico` ASC) VISIBLE,
  INDEX `idServicio_idx` (`idServicio` ASC) VISIBLE,
  CONSTRAINT `idTecnico`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `mydb`.`TECNICOS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `mydb`.`SERVICIOS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INCIDENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INCIDENTES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `tiempo_resolucion` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`CLIENTES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROBLEMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROBLEMAS` (
  `idProblema` INT NOT NULL,
  `idIncidente` INT NOT NULL,
  `idServicio` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idTecnico` INT NULL,
  `notas_tecnico` VARCHAR(45) NULL,
  PRIMARY KEY (`idProblema`),
  INDEX `idIncidente_idx` (`idIncidente` ASC) VISIBLE,
  INDEX `idServicio_idx` (`idServicio` ASC) VISIBLE,
  INDEX `idTecnico_idx` (`idTecnico` ASC) VISIBLE,
  CONSTRAINT `idIncidente`
    FOREIGN KEY (`idIncidente`)
    REFERENCES `mydb`.`INCIDENTES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `mydb`.`SERVICIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTecnico`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `mydb`.`TECNICOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTIFICACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOTIFICACIONES` (
  `id` INT NOT NULL,
  `idTecnico` INT NOT NULL,
  `estado` INT NULL,
  `idProblema` INT NOT NULL,
  `fecha_enviada` DATETIME NULL,
  `fecha_leida` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `idProblema_idx` (`idProblema` ASC) VISIBLE,
  INDEX `idTecnico_idx` (`idTecnico` ASC) VISIBLE,
  CONSTRAINT `idProblema`
    FOREIGN KEY (`idProblema`)
    REFERENCES `mydb`.`PROBLEMAS` (`idProblema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTecnico`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `mydb`.`TECNICOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
